### ISSUE TITLE
[BUG]Docker won't start

### ISSUE THREAD

**Issue by yangtfu** [telnetdoogie/synology-docker#6]
**Describe the bug**

Just ran update and cannot start docker, I'm on latest DSM 7.2.2-72806 Update 1.
```
{"action":"prepare","error":{"code":275,"description":"failed to lock packages"},"stage":"prepare","success":false}
```
**To reproduce**
1. The invoked command, e.g. `./syno_docker_update.sh update`
2. Additional steps / commands...

**Expected behavior**

**Log file**
```
Capture the exact output of the 'syno_docker_update.sh' script.
```

**Docker daemon configuration**
```
Capture the content of the file `/var/packages/Docker/etc/dockerd.json`.
```

**Additional context**

**Comment by telnetdoogie** [comment]
Can you try to run `sudo synopkg restart ContainerManager` from the command line, let me know what the output is
also please run `sudo cat /var/packages/ContainerManager/etc/dockerd.json`

**Comment by telnetdoogie** [comment]
one you've done those and posted the outputs here, to get back running again, run 

```
sudo ./syno_docker_update.sh restore \
  -b docker_backup_20240710_052312.tgz \
  -p /path/to/backup
```
...please replace the backup filename and the backup path to your backup file name and path.

That should get you up and running again.

Once you're up and running again, make sure you do a `git pull` to get the latest version (it changed earlier today)

then run 
`sudo ./syno_docker_update.sh logger`

That will (only) update the logger to the new version (does not update docker version), and will restart ContainerManager.

Assuming ContainerManager starts fine, then... 

run `sudo ./syno_docker_list_containers.sh`

...and paste the output here... (don't worry about the `docker run` stuff if you get any, just the list of containers and logger and compose entries)

**Comment by yangtfu** [comment]
> Can you try to run `sudo synopkg restart ContainerManager` from the command line, let me know what the output is also please run `sudo cat /var/packages/ContainerManager/etc/dockerd.json`

`Failed to restart package [ContainerManager], err=[0]`

```
{"data-root":"/var/packages/ContainerManager/var/docker","group":"administrators","hosts":
["unix:///var/run/docker.sock","tcp://0.0.0.0:2375"],"log-driver":"local",
"log-opts":{"max-file":"5","max-size":"20m"},"registry-mirrors":[],"storage-driver":"aufs"}
```

> one you've done those and posted the outputs here, to get back running again, run
> 
> ```
> sudo ./syno_docker_update.sh restore \
>   -b docker_backup_20240710_052312.tgz \
>   -p /path/to/backup
> ```
> 
> ...please replace the backup filename and the backup path to your backup file name and path.
> 
> That should get you up and running again.
> 
> Once you're up and running again, make sure you do a `git pull` to get the latest version (it changed earlier today)
> 
> then run `sudo ./syno_docker_update.sh logger`
> 
> That will (only) update the logger to the new version (does not update docker version), and will restart ContainerManager.
> 
> Assuming ContainerManager starts fine, then...
> 
> run `sudo ./syno_docker_list_containers.sh`
> 
> ...and paste the output here... (don't worry about the `docker run` stuff if you get any, just the list of containers and logger and compose entries)

logger update works, I've removed all the containers before update so this is the output of list_containers:
```
Container  Compose_Location Logger
   -------
```

**Comment by telnetdoogie** [comment]
So you've updated the logger... 
And your log driver looks correct.
You removed (?) containers so have none running... that's fine... How did you remove them?
I'm not sure why your storage driver is configured as `aufs`... but since we didn't change it we'll leave it as is
do another `git pull` for `synology-docker` script and let's capture the entire output of the script when you run it this time:

`sudo ./syno_docker_update.sh update`

**Comment by telnetdoogie** [comment]
FYI `{"action":"prepare","error":{"code":275,"description":"failed to lock packages"},"stage":"prepare","success":false}` usually implies there's a permissions issue or the Package Manager is doing something else at the same time, perhaps? If that error is consistent you may want to restart the NAS before trying again.

**Comment by yangtfu** [comment]
> FYI `{"action":"prepare","error":{"code":275,"description":"failed to lock packages"},"stage":"prepare","success":false}` usually implies there's a permissions issue or the Package Manager is doing something else at the same time, perhaps? If that error is consistent you may want to restart the NAS before trying again.

I ran `docker compose down` for all the stacks in terminal and updated. I tried reboot and paused cloudsync this time. But there is another error code 272 this time.
```
Update Docker Engine and Docker Compose on Synology to target version

Current DSM version: 7.2.2
Current Docker version: 20.10.23
Current Docker Compose version: 2.9.0
Target Docker version: 27.3.1
Target Docker Compose version: 2.30.3

WARNING! This will replace:
  - Docker Engine
  - Docker Compose
  - Docker daemon log driver

Are you sure you want to continue? [y/N] y
Step 1 from 10: Downloading target Docker binary (https://download.docker.com/linux/static/stable/x86_64/docker-27.3.1.tgz)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 71.8M  100 71.8M    0     0  10.1M      0  0:00:07  0:00:07 --:--:-- 11.1M
Step 2 from 10: Downloading target Docker Compose binary (https://github.com/docker/compose/releases/download/v2.30.3/docker-compose-linux-x86_64)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 61.0M  100 61.0M    0     0  8550k      0  0:00:07  0:00:07 --:--:-- 11.1M
Step 3 from 10: Stopping Docker service
{"action":"stop","beta":false,"error":{"code":0},"finished":true,"language":"enu","last_stage":"stopped","package":"ContainerManager","pid":11069,"scripts":[{"code":0,"message":"","type":"stop"}],"stage":"stopped","status":"stop","status_code":324,"status_description":"translate from systemd status","success":true,"username":"","version":"20.10.23-1437"}
Step 4 from 10: Backing up current Docker binaries (/volume1/docker/synology-docker/docker_backup_20241113_100850.tgz)
bin/
bin/docker-compose
bin/docker-proxy
bin/containerd-shim-runc-v1
bin/containerd-stress
bin/containerd-shim-runc-v2
bin/ctr
bin/containerd-shim
bin/auplink
bin/dockerd
bin/docker-init
bin/docker
bin/runc
bin/containerd
dockerd.json
start-stop-status
Step 5 from 10: Extracting target Docker binary (/tmp/docker_update/docker-27.3.1.tgz)
docker/
docker/docker-init
docker/ctr
docker/containerd
docker/containerd-shim-runc-v2
docker/dockerd
docker/docker-proxy
docker/docker
docker/runc
Step 6 from 10: Installing binaries
Step 7 from 10: Configuring log driver
Original dockerd.json file:
----------------------------

{
  "data-root": "/var/packages/ContainerManager/var/docker",
  "hosts": [
    "unix:///var/run/docker.sock",
    "tcp://0.0.0.0:2375"
  ],
  "log-driver": "db",
  "registry-mirrors": [],
  "storage-driver": "aufs"
}

Updated dockerd.json file:
----------------------------

{
  "data-root": "/var/packages/ContainerManager/var/docker",
  "hosts": [
    "unix:///var/run/docker.sock",
    "tcp://0.0.0.0:2375"
  ],
  "log-driver": "local",
  "registry-mirrors": [],
  "storage-driver": "aufs",
  "group": "administrators",
  "log-opts": {
    "max-file": "5",
    "max-size": "20m"
  }
}

Step 8 from 10: Enabling IP forwarding
Step 9 from 10: Starting Docker service - May take a while to restart 0 containers... (up to 5m)
{"action":"start","beta":false,"error":{"code":272,"description":"Failed to run script, script=[start]"},"finished":true,"language":"enu","last_stage":"prepare_start","package":"ContainerManager","pid":13157,"scripts":[{"code":1,"message":"","type":"start"}],"stage":"start_failed","status":"stop","status_code":311,"status_description":"translate from systemd status","success":false,"username":"","version":"20.10.23-1437"}
```

**Comment by telnetdoogie** [comment]
Try starting containermanager from the package center...

I've not seen this error before when trying to start the service.

**Comment by telnetdoogie** [comment]
If that doesn't work, uninstall containermanager from package center and then reinstall it. 

I'm noticing that your `dockerd.json` looks quite different from what I've seen. 

You have `aufs` as the storage driver and there's no `group` assigned. 

What NAS is this running on?
