### ISSUE TITLE
[QUESTION] should this script update dockerd too?

### ISSUE THREAD

**Issue by elegos** [telnetdoogie/synology-docker#7]
Hello,

I've run this script to update my docker version on my DS918+ with... success?

After rolling back using the original version (sigh), I kind of succesfully run this fork today.

I expected to be able to run the `docker compose` command, or seeing via `dockerd --version` the updated version, but it's not this the case.

```
➜  ~ docker --version
Docker version 27.3.1, build ce12230
➜  ~ dockerd --version
Docker version 20.10.3, build b487c8f
```

As you can see, the docker binary has been updated, though dockerd seems to be left behind (I'd expect 24.0.9)?

Thanks :)

**Comment by telnetdoogie** [comment]
```shell
➜  ~ dockerd --version
Docker version 27.3.1, build 41ca978
➜  ~ docker --version
Docker version 27.3.1, build ce12230
```

**Comment by elegos** [comment]
Should I try running the updater again?

**Comment by telnetdoogie** [comment]
what does `which dockerd` return?

**Comment by telnetdoogie** [comment]
...also... this doesn't provide `docker compose` - it still provides `docker-compose`

**Comment by elegos** [comment]
```
➜  ~ which dockerd
/usr/local/bin/dockerd
```

Isn't `docker compose` part of docker, nowadays? Maybe I misunderstood it, though on my linux machine is like that by default (with the CE version)

**Comment by elegos** [comment]
```
➜  bin cd /var/packages/Docker/target/usr/bin 
➜  bin ls -l *docker*
-rwxr-xr-x 1 root root 39536632 Nov 12 17:43 docker
-rwxr-xr-x 1 root root 64044374 Nov 12 17:43 docker-compose
-rwxr-xr-x 1 root root 66233896 Jul 21  2022 dockerd
-rwxr-xr-x 1 root root   708448 Nov 12 17:43 docker-init
-rwxr-xr-x 1 root root  2074741 Nov 12 17:43 docker-proxy
````
apparently dockerd skipped the update process

**Comment by telnetdoogie** [comment]
When this script updates the docker binaries, it simply takes all of the binaries from the latest docker download (in my case, https://download.docker.com/linux/static/stable/x86_64/docker-27.3.1.tgz and overwrites all of the files into `/var/packages/ContainerManager/target/usr/bin/docker`.

It's possible that at some point someone "manually" updated dockerd on your box so that `/usr/local/bin/dockerd` is no longer a symbolic link to the docker package any more, and rather the binary itself.

```shell
➜  bin ls -al /usr/local/bin/d*
lrwxrwxrwx 1 root root 40 Nov  9 05:28 /usr/local/bin/dc -> /var/packages/synocli-misc/target/bin/dc
lrwxrwxrwx 1 root root 41 Nov  5 10:18 /usr/local/bin/delv -> /var/packages/synocli-net/target/bin/delv
lrwxrwxrwx 1 root root 43 Nov 11 16:47 /usr/local/bin/detox -> /var/packages/synocli-file/target/bin/detox
lrwxrwxrwx 1 root root 40 Nov  5 10:18 /usr/local/bin/dig -> /var/packages/synocli-net/target/bin/dig
lrwxrwxrwx 1 root root 52 Nov 11 16:27 /usr/local/bin/docker -> /var/packages/ContainerManager/target/usr/bin/docker
lrwxrwxrwx 1 root root 60 Nov 11 16:27 /usr/local/bin/docker-compose -> /var/packages/ContainerManager/target/usr/bin/docker-compose
lrwxrwxrwx 1 root root 53 Nov 11 16:27 /usr/local/bin/dockerd -> /var/packages/ContainerManager/target/usr/bin/dockerd
lrwxrwxrwx 1 root root 57 Nov 11 16:27 /usr/local/bin/docker-init -> /var/packages/ContainerManager/target/usr/bin/docker-init
lrwxrwxrwx 1 root root 57 Nov 11 16:27 /usr/local/bin/docker_inspect -> /var/packages/ContainerManager/target/tool/docker_inspect
lrwxrwxrwx 1 root root 58 Nov 11 16:27 /usr/local/bin/docker-proxy -> /var/packages/ContainerManager/target/usr/bin/docker-proxy
lrwxrwxrwx 1 root root 46 Nov 11 16:47 /usr/local/bin/dos2unix -> /var/packages/synocli-file/target/bin/dos2unix
```

**Comment by telnetdoogie** [comment]
I suspect the above is what has happened for you... it seems 'incredible' that JUST the `dockerd` would not have copied.. there's no logic in the script for that to happen

If that's the case, to 'repair' it:

```
sudo rm /usr/local/bin/dockerd
sudo ln -s /var/packages/ContainerManager/target/usr/bin/dockerd /usr/local/bin/dockerd
```

**Comment by telnetdoogie** [comment]
if you run 
```
sudo stat `which dockerd`
```
you'll see if it's resolving to the file in /usr/local/bin or to the actual ContainerManager target.

```console
sudo stat `which dockerd`
  File: /usr/local/bin/dockerd -> /var/packages/ContainerManager/target/usr/bin/dockerd
  Size: 53              Blocks: 0          IO Block: 4096   symbolic link
Device: 900h/2304d      Inode: 38762       Links: 1
Access: (0777/lrwxrwxrwx)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2024-11-11 16:27:11.353058224 -0600
Modify: 2024-11-11 16:27:11.353058224 -0600
Change: 2024-11-11 16:27:11.353058224 -0600
 Birth: -
```

**Comment by elegos** [comment]
It is all fine:

```
sudo stat `which dockerd`
  File: /usr/local/bin/dockerd -> /var/packages/Docker/target/usr/bin/dockerd
  Size: 43              Blocks: 0          IO Block: 4096   symbolic link
Device: 900h/2304d      Inode: 34312       Links: 1
Access: (0777/lrwxrwxrwx)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2024-11-12 17:04:06.472853144 +0100
Modify: 2024-11-12 17:04:06.472853144 +0100
Change: 2024-11-12 17:04:06.472853144 +0100
 Birth: -
```

If I try to manually update dockerd though this happens:
```cp: cannot create regular file './dockerd': Text file busy```

- given that I stopped the ContainerManager service first (`ps aux|grep dockerd` shows only the grep itself)

Should I try restarting the NAS?

**Comment by telnetdoogie** [comment]
What version of DSM are you running?

**Comment by telnetdoogie** [comment]
I've never seen this issue. Did you see that`cp: cannot create regular file './dockerd': Text file busy` error output when you were running the update?

**Comment by telnetdoogie** [comment]
you could try adding the downloaded `dockerd` to /var/packages/Docker/target/usr/bin/dockerd2
and then replacing the symbolic link to point to it, then restarting.
Once that works, copy dockerd2 in /var/packages/Docker/target/usr/bin/dockerd2 to dockerd
Then replace the symlink again, with one more reboot.

You mentioned stopping ContainerManager... based on your paths it looks like you're on an old DSM so you might need to stop 'docker' versus 'ContainerManager'.

**Comment by elegos** [comment]
> I've never seen this issue. Did you see that`cp: cannot create regular file './dockerd': Text file busy` error output when you were running the update?

Not that I am aware of, but might have been the case.

Version of DSM is: DSM 7.1.1-42962 Update 6 (latest available for my system)

**Comment by elegos** [comment]
> you could try adding the downloaded `dockerd` to /var/packages/Docker/target/usr/bin/dockerd2 and then replacing the symbolic link to point to it, then restarting. Once that works, copy dockerd2 in /var/packages/Docker/target/usr/bin/dockerd2 to dockerd Then replace the symlink again, with one more reboot.
> 
> You mentioned stopping ContainerManager... based on your paths it looks like you're on an old DSM so you might need to stop 'docker' versus 'ContainerManager'.

I will try with the dockerd2 "trick" and see if, reboot after reboot, I can "move" dockerd2 back to dockerd, updating the symlink between the reboots

**Comment by telnetdoogie** [comment]
You could also just make sure that the `docker` service is truly shut down... I haven't done a ton of testing on 7.1 prior to the "ContainerManager" service. You should be starting / stopping the service like `synopkg stop pkgctl-Docker`  I think.

It shouldn't really require a reboot but if something has a hold of that `dockerd` file then...

**Comment by telnetdoogie** [comment]
if your `pkgctl-Docker` service is truly stopped and `dockerd` is still in use... something funky is happening.

**Comment by telnetdoogie** [comment]
> Isn't `docker compose` part of docker, nowadays? Maybe I misunderstood it, though on my linux machine is like that by default (with the CE version)

`docker compose` is a plugin for docker. On linux systems you install it seperately (unless you're installing Docker Desktop)
There's really no functional difference between `docker-compose` and `docker compose` , but installing the plugin on Synology would be a bit more complex and not sure there's any real benefit

**Comment by elegos** [comment]
Ok, I've downloaded and installed DSM 7.2.2 and docker returned to version 20.10.23.

Now, it is suggested to down all docker-compose environments, though I have some volumes that I want to keep intact (and down will remove them AFAIK). Is there a way to keep them, so that I can restore them again once finished? Or should I continue and force recreate the containers at a later stage perhaps?

**Comment by elegos** [comment]
Ah, the safest way is what I did: just run the update and then recreate the containers via `sudo docker-compose up -d --force-recreate` 👍
